---
title: "monographs code seedlings"
author: "Colleen Cosgrove"
date: "March 8, 2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
library(data.table)
library(gtools)
library(vegan)
library(MASS)
##Load the Data
juvies=read.csv("C:/Users/crc31/OneDrive/Documents/School/Research/Data/Trees/JuvenileMatrix.csv")
seeds=read.csv("C:/Users/crc31/OneDrive/Documents/School/Research/Data/Trees/SeedlingMatrix.csv")
soildata=read.csv("C:/Users/crc31/OneDrive/Documents/School/Grad School/SpatialStats/soil data May 08 for tree plots.csv")
oldtreedata=read.csv("C:/Users/crc31/Dropbox/Jennings 2016/tree basal areas.csv")
treedata=read.csv("C:/Users/crc31/Dropbox/Jennings 2016/New Adult Basal Area.csv")

seeds[is.na(seeds)]<-0

#sum rings
tree.ringsum=oldtreedata[1:83,]
for(i in 1:83) {
  tree.ringsum[i,10:42]=oldtreedata[i,10:42]+oldtreedata[i+83,10:42]+oldtreedata[i+166,10:42]  }
rownames(tree.ringsum)=tree.ringsum[,1]
tree.ringsum

treedata=treedata[c(1:266,268:290),]
newtree.ringsum=treedata[1:96,]
colnames(treedata)
for(i in 1:96) {
  newtree.ringsum[i,10:44]=treedata[i,10:44]+treedata[i+96,10:44]+treedata[i+192,10:44]  }
rownames(newtree.ringsum)=newtree.ringsum$Plot
newtree.ringsum[is.na(newtree.ringsum)]<-0
newtree.ringsum
dim(seeds)
colnames(seeds)
addseeds=cbind(seeds[,c(1,5:38)])
#add _seed to all of the seedling species columns
colnames(addseeds)=paste(colnames(addseeds), "seed", sep = "_")
colnames(addseeds)[1]="Plot"
colnames(addseeds)
#put everything back together and then add the adult dataset
seeds=merge(seeds[,c(1:4)], addseeds)
seeds[is.na(seeds)]<-0
dim(seeds)
seeds=merge(seeds,soildata)
dim(seeds)
seeds.tree=merge(seeds,newtree.ringsum, by="Plot")
head(seeds.tree)
#Hellinger Transform data
colnames(seeds.tree)
tree.rowsums=apply(seeds.tree[5:38],1,sum)
seeds.tree[,5:38]=seeds.tree[,5:38]/tree.rowsums
seeds.tree[,5:38]=sqrt(seeds.tree[,5:38])

#### Forward selection using regionalized soil variables
# First we have to merge the datasets
#Combine ecosystem type and soil variables into the seedling and juvenile datasets
tree.hel.soil=seeds.tree
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
tree.hel.soil1=tree.hel.soil
```
NOTE: Each chunk has code for core/core+edge/core+edge+transition.
Each chunk with a * in the title contains significant values in an RDA of species~soil variables broken into long/short/nug as separate models.
```{r ACERUB*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,6], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,6], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)


#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,6], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,6], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)
RsquareAdj(hel.rda.fulsoil_long)
global.thresh=RsquareAdj(hel.rda.fulsoil_long)$adj.r.squared


#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,6], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,6], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,6]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,6], tree.hel.soil[,65:72])

hel.rda.fulsoil.full=rda(tree.hel.soil[,6]~tree.hel.soil$Ptot_short+tree.hel.soil$Po_short+tree.hel.soil$pH_short+tree.hel.soil$moist_short+tree.hel.soil$ps1_short+tree.hel.soil$percc_short+tree.hel.soil$pomc_short+tree.hel.soil$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel #whole model

# Constructing a model with selected variables.
#hel.rda.selsoil = rda(tree.hel.soil[,6] ~ as.matrix(tree.hel.soil[,c(35,37,39,41)]))
#anova(hel.rda.selsoil)
#RsquareAdj(hel.rda.selsoil)
#plot(hel.rda.selsoil)
```
```{r ACESAC}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,7], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,7], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,7], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,7], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,7], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,7], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)
```
```{r FAGAME*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,48:55]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,18], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,18], tree.hel.soil[,c(65:72)]) #variables_long. insignificant
anova(hel.rda.fulsoil_short)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,18]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,65:72])

hel.rda.fulsoil.full=rda(tree.hel.soil[,18]~tree.hel.soil$Ptot_short+tree.hel.soil$Po_short+tree.hel.soil$pH_short+tree.hel.soil$moist_short+tree.hel.soil$ps1_short+tree.hel.soil$percc_short+tree.hel.soil$pomc_short+tree.hel.soil$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel #whole model

# Constructing a model with selected variables.
#hel.rda.selsoil = rda(tree.hel.soil[,18] ~ as.matrix(tree.hel.soil[,c(35,37,39,41)]))
#anova(hel.rda.selsoil)
#RsquareAdj(hel.rda.selsoil)
#plot(hel.rda.selsoil)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,c(48:55)]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,18], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,18], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.038. 
anova(hel.rda.fulsoil_short)
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,65:72])
anova(hel.rda.fulsoil)

#Run forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,18]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,65:72])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10:24]~tree.hel.soil$Ptot_short+tree.hel.soil$Po_short+tree.hel.soil$pH_short+tree.hel.soil$moist_short+tree.hel.soil$ps1_short+tree.hel.soil$percc_short+tree.hel.soil$pomc_short+tree.hel.soil$cton_short)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,67])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared
##Only significant variable: pH_short.

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,48:55]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,18], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,18], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r QUERUB}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,32], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,32], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,32], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,32], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,32], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,32], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)
```
```{r cAROVA}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,11], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,11], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,11], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,11], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,11], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,11], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)
```
```{r FRAAME*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,19], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,19], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.028
anova(hel.rda.fulsoil_long)
#Run forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,19]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,19], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,19]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long +tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
###The full long model is a better relation than any individual variable.
#hel.rda.fulsoil = rda(tree.hel.soil[,19], tree.hel.soil[,67])
#anova(hel.rda.fulsoil)
#RsquareAdj(hel.rda.fulsoil)
#global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,19], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,19], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,19], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,19], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r PRUSER*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Forward Selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,28]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,28], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,28]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long+tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
##Variables: percc_long; moist_long; cton_long

hel.rda.fulsoil = rda(tree.hel.soil[,28], tree.hel.soil[,c(45,51,55)])
anova(hel.rda.fulsoil)
RsquareAdj(hel.rda.fulsoil)
global.thresh=RsquareAdj(hel.rda.fulsoil)$adj.r.squared

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,28], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,28], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,c(48:55)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,28], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,28], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.008
anova(hel.rda.fulsoil_short)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,28]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,28], tree.hel.soil[,65:72])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10:24]~tree.hel.soil$Ptot_nug+tree.hel.soil$Po_nug+tree.hel.soil$pH_nug+tree.hel.soil$moist_nug+tree.hel.soil$ps1_nug+tree.hel.soil$ps2_nug+tree.hel.soil$percc_nug+tree.hel.soil$pomc_nug+tree.hel.soil$cton_nug)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
###The full model is more appropriate than any particular variable

# Constructing a model with selected variables.
#hel.rda.selsoil = rda(tree.hel.soil[,28] ~ as.matrix(tree.hel.soil[,c(65:72)]))
#anova(hel.rda.selsoil)
#RsquareAdj(hel.rda.selsoil)
#plot(hel.rda.selsoil)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,48:55]) #variables_long. significant: p=0.002
anova(hel.rda.fulsoil_long)

#Forward Selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,28]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,28], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,28]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long +tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,28] ~ as.matrix(tree.hel.soil[,c(45,51,55)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,28], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,28], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r QUEALB}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,29], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,29], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,29], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,29], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,29], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,29], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,29], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,29], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,29], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)
```
```{r LIRTUP}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,23], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,23], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,c(48:55)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,23], tree.hel.soil[,c(56:64)]) #variables_nug. not enough data
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,23], tree.hel.soil[,c(65:72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,23], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,23], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r OSTVIR}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,26], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,26], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,26], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,26], tree.hel.soil[,c(48:55)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,26], tree.hel.soil[,c(56:64)]) #variables_nug. not enough data
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,26], tree.hel.soil[,c(65:72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,26], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,26], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,26], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r CARCAR*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,9], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,9], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,c(48:55)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,9], tree.hel.soil[,c(56:64)]) #variables_nug. significant: p=0.029
anova(hel.rda.fulsoil_nug)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,9]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,9], tree.hel.soil[,56:64])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10:24]~tree.hel.soil$Ptot_nug+tree.hel.soil$Po_nug+tree.hel.soil$pH_nug+tree.hel.soil$moist_nug+tree.hel.soil$ps1_nug+tree.hel.soil$ps2_nug+tree.hel.soil$percc_nug+tree.hel.soil$pomc_nug+tree.hel.soil$cton_nug)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,9] ~ as.matrix(tree.hel.soil[,c(58)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_short = rda(tree.hel.soil[,9], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,9], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,9], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r NYSSYL}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,25], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,25], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,25], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,25], tree.hel.soil[,c(48:55)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,25], tree.hel.soil[,c(56:64)]) #variables_nug. not enough data
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,25], tree.hel.soil[,c(65:72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,25], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,25], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,25], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```

```{r CARCOR*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,48:55]) #variables_long. significant: p=0.004
anova(hel.rda.fulsoil_long)

##Forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,10]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,10], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long +tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,10] ~ as.matrix(tree.hel.soil[,c(45)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,10], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,10], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,c(48:55)]) #variables_long. significant: p=0.014
anova(hel.rda.fulsoil_long)

##Forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,10]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,10], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long +tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
#Ptot_long

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,10] ~ as.matrix(tree.hel.soil[,c(56)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,10], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,10], tree.hel.soil[,c(65:72)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,48:55]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

##Forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,10]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,10], tree.hel.soil[,48:55])

hel.rda.fulsoil.full=rda(tree.hel.soil[,10]~tree.hel.soil$Ptot_long+tree.hel.soil$Po_long+tree.hel.soil$pH_long+tree.hel.soil$moist_long +tree.hel.soil$ps1_long+tree.hel.soil$ps2_long+tree.hel.soil$percc_long+tree.hel.soil$cton_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel
#pH_long and moist_long

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,10] ~ as.matrix(tree.hel.soil[,c(50:51)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_nug=rda(tree.hel.soil[,10], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,10], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r QUEPAL}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,31], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,31], tree.hel.soil[,c(65:72)]) #variables_long. nto significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,c(48:55)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,31], tree.hel.soil[,c(56:64)]) #variables_nug. not enough data
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,31], tree.hel.soil[,c(65:72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,31], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,31], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r ULMSP}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,38], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,38], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,c(48:55)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,38], tree.hel.soil[,c(56:64)]) #variables_nug. not enough data
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,38], tree.hel.soil[,c(65:72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,38], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,38], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```
```{r FRANIG*}
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,20], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,20], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,c(48:55)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,20], tree.hel.soil[,c(56:64)]) #variables_nug. significant: p=0.012
anova(hel.rda.fulsoil_nug)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,20]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,20], tree.hel.soil[,56:64])

hel.rda.fulsoil.full=rda(tree.hel.soil[,20]~tree.hel.soil$Ptot_nug+tree.hel.soil$Po_nug+tree.hel.soil$pH_nug+tree.hel.soil$moist_nug+tree.hel.soil$ps1_nug+tree.hel.soil$ps2_nug+tree.hel.soil$percc_nug+tree.hel.soil$pomc_nug+tree.hel.soil$cton_nug)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel

# Constructing a model with selected variables.
hel.rda.selsoil = rda(tree.hel.soil[,20] ~ as.matrix(tree.hel.soil[,c(56)]))
anova(hel.rda.selsoil)
RsquareAdj(hel.rda.selsoil)
plot(hel.rda.selsoil)

#Back to RDAs
hel.rda.fulsoil_short = rda(tree.hel.soil[,20], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,48:55]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
hel.rda.fulsoil_nug=rda(tree.hel.soil[,20], tree.hel.soil[,c(56:64)]) #variables_nug. not significant.
anova(hel.rda.fulsoil_nug)
hel.rda.fulsoil_short = rda(tree.hel.soil[,20], tree.hel.soil[,c(65:72)]) #variables_long. not significant
anova(hel.rda.fulsoil_short)
```


LETS Do this all over again, but with ONLY the soil variable(s) associated with adult trees.


```{r ACERUB}
#ACERUB is associated with Ptot_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,48]) #variables_long. not significant
anova(hel.rda.fulsoil_long)


#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,c(48)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)


#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,6], tree.hel.soil[,48]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r ACESAC}
##ACESAC adults are correlated with Ptot_long, pH_long, ps1_long, cton_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,c(48,50,52,72)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,c(48,50,52,72)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,7], tree.hel.soil[,c(48,50,52,72)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r FAGAME*}
###FAGAME adults are correlated with pH_long, Ptot_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,c(50,48)]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)

##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,18]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,c(50,48)])

hel.rda.fulsoil.full=rda(tree.hel.soil[,18]~tree.hel.soil$Ptot_long+tree.hel.soil$pH_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel #whole model

# Constructing a model with selected variables.
#hel.rda.selsoil = rda(tree.hel.soil[,18] ~ as.matrix(tree.hel.soil[,c(35,37,39,41)]))
#anova(hel.rda.selsoil)
#RsquareAdj(hel.rda.selsoil)
#plot(hel.rda.selsoil)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,c(50,48)]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,18], tree.hel.soil[,50,48]) #variables_long. insignificant
anova(hel.rda.fulsoil_long)
##NEW forward selection
hel.rda.fulsoil.none = rda(tree.hel.soil[,18]~1)
hel.rda.fulsoil = rda(tree.hel.soil[,18], tree.hel.soil[,c(50,48)])

hel.rda.fulsoil.full=rda(tree.hel.soil[,18]~tree.hel.soil$Ptot_long+tree.hel.soil$pH_long)

tree.sel=ordiR2step(hel.rda.fulsoil.none,scope=formula(hel.rda.fulsoil.full),Pin=0.05,R2scope=TRUE)
tree.sel #whole model

# Constructing a model with selected variables.
#hel.rda.selsoil = rda(tree.hel.soil[,18] ~ as.matrix(tree.hel.soil[,c(35,37,39,41)]))
#anova(hel.rda.selsoil)
#RsquareAdj(hel.rda.selsoil)
#plot(hel.rda.selsoil)
```
```{r QUERUB}
###QUERUB adults are correlated with pomc_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,71]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,c(71)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,32], tree.hel.soil[,71]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
```
```{r cAROVA}
###CAROVA adults are correlated with pH_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,50]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,c(50)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,11], tree.hel.soil[,50]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
```
```{r FRAAME}
###FRAAME adults are correlated with moist_long, Po_long, percc_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,c(51,49,54)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,c(51,49,54)]) #variables_long. significant: p=0.028
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,19], tree.hel.soil[,c(51,49,54)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r PRUSER*}
###PRUSER adults are correlated with pH_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,67]) #variables_long. significant: p=0.017
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.1725
global.thresh=RsquareAdj(hel.rda.fulsoil_long)$adj.r.squared

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,c(67)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.2755

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,28], tree.hel.soil[,67]) #variables_long. significant: p=0.002
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.1708
```
```{r QUEALB}
###QUEALB adults are not correlated with any particular variable
```
```{r LIRTUP}
###LIRTUP adults are correlated with percc_short & moist_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,c(70,68)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,c(70,68)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,23], tree.hel.soil[,c(70,68)]) #variables_long. significant: p=0.006
anova(hel.rda.fulsoil_long)
```
```{r OSTVIR}
###OSTVIR adults are not correlated with any particular variables.
```
```{r CARCAR}
###CARCAR adults are correlated with ptot_short, moist_long, ps1_nug
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,c(65,51,60)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,c(65,51,60)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,9], tree.hel.soil[,c(65,51,60)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r NYSSYL}
###NYSSYL adults are not correlated with any particular soil variable
```

```{r CARCOR*}
###CARCOR adults are correlated with ptot_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,48]) #variables_long. significant: p=0.001
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.296

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,c(48)]) #variables_long. significant: p=0.001
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.652

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,10], tree.hel.soil[,48]) #variables_long. significant: p=0.002
anova(hel.rda.fulsoil_long)
RsquareAdj(hel.rda.fulsoil_long) #0.315
```
```{r QUEPAL}
###QUEPAL adults are associated with moist_long & pH_long
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,c(51,50)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,c(51,50)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,31], tree.hel.soil[,c(51,50)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r ULMSP}
###ULMSP adults are correlated with Po_short & cton_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,c(66,72)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,c(66,72)]) #variables_long. not enough data
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,38], tree.hel.soil[,c(66,72)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```
```{r FRANIG}
###FRANIG adults are correlated with ptot_long, percc_long, moist_short
tree.hel.soil=tree.hel.soil1
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
colnames(tree.hel.soil)
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,c(48,54,68)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core Plots
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
dim(tree.hel.soil)
colnames(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,c(48,54,68)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)

#Core + edge Plots
tree.hel.soil=tree.hel.soil1
tree.hel.soil=tree.hel.soil[tree.hel.soil$Transect.x=="Core"|tree.hel.soil$Transect.x=="Edge",]
rownames(tree.hel.soil)=tree.hel.soil[,1]
tree.hel.soil=na.exclude(tree.hel.soil)
colnames(tree.hel.soil)
dim(tree.hel.soil)
# Here is the global analysis. Can proceed if significant.  Use adj. R square as additional stopping criterion.
hel.rda.fulsoil_long = rda(tree.hel.soil[,20], tree.hel.soil[,c(48,54,68)]) #variables_long. not significant
anova(hel.rda.fulsoil_long)
```